### ISSUE TITLE
host util genext2fs is not enabled by default

### ISSUE THREAD

**Issue by nabav100** [mendersoftware/buildroot-mender#2]
The buildroot make command fails at one of the last steps.

The following needs to be defined:
BR2_PACKAGE_HOST_GENEXT2FS=y

**Comment by mirzak** [comment]
Thanks @nabav100. Would make sense to add it to the common [defconfig](https://github.com/mendersoftware/buildroot-mender/blob/master/buildroot-external-mender/board/common/mender-common.cfg). Mind creating a PR?

**Comment by aduskett** [comment]
Hey @nabav100 , I know this is ancient, but I took over the repository today and plan on remaking it from the ground up. I'll be sure to add this immediately!

**Comment by aduskett** [comment]
I think I fixed the problem and the config now builds.
