### ISSUE TITLE
Can I get push access to this repository?

### ISSUE THREAD

**Issue by aduskett** [mendersoftware/buildroot-mender#4]
Hello, I have been working hard to integrate new mender updates to Buildroot. I have submitted patches to upstream Buildroot, but the maintainers do not seem interested in maintaining the packages in a timely manner (some package updates will sit for 4+ months before being reviewed.)

In the meantime, it would be nice if I could have an official place to support an up-to-date mender on Builldroot.

Let me know if you are OK with it!

Thanks!

**Comment by TheYoctoJester** [comment]
Hi @aduskett,

You definitely can! The only thing I would ask for right away, can you add a note to the README that the repository is not under active maintenance by NT?

Greets,
Josef

**Comment by lluiscampos** [comment]
Hi @aduskett, I just sent you the invite :+1:

**Comment by aduskett** [comment]
> Hi @aduskett,
> 
> You definitely can! The only thing I would ask for right away, can you add a note to the README that the repository is not under active maintenance by NT?
> 
> Greets, Josef

Thank you so much Josef! Of course I will!

**Comment by aduskett** [comment]
> Hi @aduskett, I just sent you the invite 👍

Thank you so much!
